import fs from 'node:fs';
import {Button,SearchInput,Checkbox,SegmentedControl,Panel,Badge,EmptyState} from './components.mjs';
const b=(content,variant='secondary',attributes={})=>Button({content,variant,attributes});
const variants=[['primary','主要操作','保存设置'],['secondary','次要操作','取消'],['tertiary','低强调操作','查看详情'],['danger','破坏性操作','删除草稿']];
const row=(state,opts={})=>`<tr><th>${state}</th>${variants.map(([variant,,content])=>`<td>${Button({content,variant,...opts})}</td>`).join('')}</tr>`;
const states=Panel({attributes:{id:'state-panel'},content:EmptyState({title:'运行记录已就绪',description:'此区域仅演示共享组件状态，不会创建或修改业务数据。'})});
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Forge 设计系统 · Geist v1</title><link rel="stylesheet" href="/design-system/tokens.css"><link rel="stylesheet" href="/design-system/components.css"><link rel="stylesheet" href="/design-system/gallery.css"></head>
<body class="fg-theme"><main class="fg-gallery"><header><div><h1>Forge 设计系统</h1><p>Geist 基础 · 第一阶段 · 组件与状态</p></div><a class="fg-button" href="/forge.html?view=runs">打开运行记录样板</a></header>
<nav aria-label="展示目录"><a href="#buttons">按钮</a><a href="#forms">表单</a><a href="#states">状态与容器</a><a href="#foundations">设计基础</a></nav>
<section id="buttons"><h2>按钮</h2><p>操作角色决定样式；成功、失败和运行中由状态标签表达。每个独立任务区域通常只保留一个明显的主要操作。</p><div class="fg-gallery-table"><table><thead><tr><th>状态</th>${variants.map(([,name])=>`<th>${name}</th>`).join('')}</tr></thead><tbody>${row('默认')}${row('禁用',{disabled:true})}${row('处理中',{loading:true})}</tbody></table></div><p class="fg-muted">示例按钮仅用于检查 hover、pressed、Tab focus 和 disabled。处理中保持宽度与键盘焦点，阻止重复激活。</p>
<div class="fg-demo-row">${Button({content:'紧凑 32',size:'sm'})}${b('默认 40')}${Button({content:'宽松 48',size:'lg'})}${b('文字链接','link')}</div></section>
<section id="forms"><h2>表单</h2><div class="fg-form-grid"><form id="demo-form" novalidate><label for="demo-name">运行名称 <span class="fg-muted">（必填）</span></label><input id="demo-name" class="fg-input" aria-describedby="name-hint name-error" placeholder="例如：中国地标组"><p id="name-hint" class="fg-muted">仅在本展示入口验证，不保存业务数据。</p><p id="name-error" class="fg-form-error" role="alert"></p><div class="fg-demo-row">${Button({content:'验证名称',variant:'primary',attributes:{type:'submit'}})}${b('重置','secondary',{type:'reset'})}</div><p id="form-result" role="status"></p></form><div><label for="demo-provider">供应商</label><select id="demo-provider" class="fg-select"><option>全部供应商</option><option>供应商 A · 示例</option></select><p class="fg-muted">选择器沿用原生键盘与系统弹层。</p>${SearchInput({label:'搜索组件',placeholder:'搜索组件…',attributes:{id:'demo-search'}})}<p id="search-result" role="status"></p>${Checkbox({label:'只看我的'})}</div></div></section>
<section id="states"><h2>状态与容器</h2><div class="fg-demo-row">${[['success','技术成功'],['running','运行中'],['warning','部分失败'],['danger','失败'],['neutral','待审核']].map(([tone,label])=>Badge({tone,label})).join('')}</div><p>技术成功仍可处于待审核，颜色不改变业务含义。</p>
${SegmentedControl({label:'容器状态预览',content:[['ready','就绪'],['loading','加载'],['empty','空'],['error','错误']].map(([state,label])=>b(label,'tertiary',{'data-preview-state':state,'aria-pressed':String(state==='ready')})).join('')})}
${states}<p id="state-announcement" class="fg-sr-only" role="status"></p>
<template id="state-ready">${EmptyState({title:'运行记录已就绪',description:'此区域仅演示共享组件状态，不会创建或修改业务数据。'})}</template>
<template id="state-loading"><div class="fg-gallery-loading" role="status" aria-busy="true"><p>正在加载运行记录…</p><div class="fg-skeleton"></div><div class="fg-skeleton"></div><div class="fg-skeleton"></div></div></template>
<template id="state-empty">${EmptyState({title:'没有匹配的运行',description:'试试其他关键词，或清除当前筛选。',action:b('清除筛选','secondary',{'data-preview-state':'ready'})})}</template>
<template id="state-error"><div class="fg-empty"><h2>运行记录加载失败</h2><p class="fg-form-error" role="alert">当前无法获取数据，请重试。已有筛选条件应当保留。</p>${b('重试','secondary',{'data-preview-state':'ready'})}</div></template>
</section>
<section id="foundations"><h2>设计基础</h2><div class="fg-foundation-grid"><div><h3>语义颜色</h3><dl><dt>主要文字 / 主操作</dt><dd>#171717</dd><dt>次要文字</dt><dd>#666666</dd><dt>工作区 / 弱背景</dt><dd>#FFFFFF / #FAFAFA</dd><dt>分区 / 控件边框</dt><dd>#EAEAEA / #C9C9C9</dd><dt>焦点</dt><dd>#0068D6</dd></dl></div><div><h3>排版与尺寸</h3><p>Geist Sans + 中文系统字体<br>Geist Mono 用于 ID、代码与费用</p><p>标题 24 / 32，区块 20 / 28<br>正文 14 / 22，辅助 13 / 20、12 / 18</p><p>间距 4、8、12、16、20、24、32、40、48<br>圆角 4 / 6 / 8；控件 32 / 40 / 48</p></div></div></section>
<footer>Forge 原型 · 共享源文件生成 · 未连接后端的状态仅用于展示验证</footer></main><script type="module" src="/design-system/gallery.mjs"></script></body></html>`;
fs.writeFileSync(new URL('../../public/design-system.html',import.meta.url),html);
console.log('Generated /design-system.html from shared primitives');
// Responsive QA uses the real prototype in a 390px browsing context.
fs.writeFileSync(new URL('../../public/design-system-responsive.html',import.meta.url),`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forge · 390px 响应式验证</title><link rel="stylesheet" href="/design-system/tokens.css"><link rel="stylesheet" href="/design-system/components.css"><style>body{margin:24px;background:var(--fg-background-subtle)}h1{font-size:20px;margin-bottom:8px}p{color:var(--fg-text-secondary)}iframe{display:block;width:390px;max-width:100%;height:844px;border:1px solid var(--fg-border);background:white}a{color:var(--fg-text)}</style></head><body class="fg-theme"><h1>运行记录 · 390px</h1><p>真实原型的窄屏浏览上下文 · <a href="/design-system.html">返回组件展示</a></p><iframe src="/forge.html?view=runs" title="运行记录窄屏预览"></iframe></body></html>`);
